in-line docker-build to avoid rootdir shenanigans

diff --git a/bin/docker-build-policy-controller b/bin/docker-build-policy-controller
--- a/bin/docker-build-policy-controller
+++ b/bin/docker-build-policy-controller
@@ -14,7 +14,36 @@ rootdir=$( cd "$bindir"/.. && pwd )
 . "$bindir"/_docker.sh
 # shellcheck source=_tag.sh
 . "$bindir"/_tag.sh
+# shellcheck source=_log.sh
+. "$bindir"/_log.sh
 
-dockerfile=$rootdir/policy-controller/Dockerfile
 tag=$(head_root_tag)
-docker_build policy-controller "$tag" "$dockerfile" --build-arg LINKERD_VERSION="$tag"
+
+cache_params=""
+if [ -n "$DOCKER_BUILDKIT_CACHE" ]; then
+    cache_params="--cache-from type=local,src=${DOCKER_BUILDKIT_CACHE} --cache-to type=local,dest=${DOCKER_BUILDKIT_CACHE},mode=max"
+fi
+
+output_params="--load"
+if [ -n "$DOCKER_MULTIARCH" ]; then
+    output_params="--platform $SUPPORTED_ARCHS"
+    if [ -n "$DOCKER_PUSH" ]; then
+        output_params+=" --push"
+    else
+        echo "Error: env DOCKER_PUSH=1 is missing"
+        echo "When building the multi-arch images it is required to push the images to the registry"
+        echo "See https://github.com/docker/buildx/issues/59 for more details"
+        exit 1
+    fi
+fi
+
+repo=$(docker_repo policy-controller)
+
+log_debug "  :; docker buildx policy-controller $cache_params $output_params -t $repo:$tag $*"
+# shellcheck disable=SC2086
+docker buildx build policy-controller \
+    $cache_params \
+    $output_params \
+    -t "$repo:$tag"
+
+echo "$repo:$tag"
