ci: Fix PAT configuration in sync-proxy
The fetch-proxy script uses the GITHUB_TOKEN environment variable. This
fixes this and also improves error handling in fetch-proxy.

diff --git a/bin/fetch-proxy b/bin/fetch-proxy
--- a/bin/fetch-proxy
+++ b/bin/fetch-proxy
@@ -37,23 +37,28 @@ cd "$builddir"
 
 version=${1:-latest}
 arch=${2:-amd64}
-if [ "$version" = latest ]; then
-  ghcurl "$releases_url"/latest > release.json
-  version=$(jq -r .tag_name release.json | sed 's,^'"${release_prefix}"',,')
-else
-  tag="${release_prefix}${version}"
-  ghcurl "$releases_url"/tags/"$(printf "$tag" | jq -sRr @uri)" > release.json
+tag="${release_prefix}${version}"
+release_url="$releases_url"/tags/"$(printf "$tag" | jq -sRr @uri)"
+if ! ghcurl "$release_url" > release.json ; then
+  echo "Failed to fetch $release_url" >&2
+  exit 1
 fi
 
 pkgname="linkerd2-proxy-${version}-${arch}"
 
 pkgfile="${pkgname}.tar.gz"
 pkgurl=$(jq -r '.assets[] | select(.name == "'"$pkgfile"'") | .url' release.json)
-ghcurl -H 'Accept: application/octet-stream' -o "$pkgfile" "$pkgurl"
+if ! ghcurl -H 'Accept: application/octet-stream' -o "$pkgfile" "$pkgurl" ; then
+  echo "Failed to fetch $pkgurl" >&2
+  exit 1
+fi
 
 shafile="${pkgname}.txt"
 shaurl=$(jq -r '.assets[] | select(.name == "'"$shafile"'") | .url' release.json)
-ghcurl -H 'Accept: application/octet-stream' -o "$shafile" "$shaurl"
+if ! ghcurl -H 'Accept: application/octet-stream' -o "$shafile" "$shaurl" ; then
+  echo "Failed to fetch $shaurl" >&2
+  exit 1
+fi
 
 tar -zxvf "$pkgfile" >&2
 expected=$(awk '{print $1}' "$shafile")
