build: Update fetch-proxy to support alternate repos (#12135)
* build: Update fetch-proxy to support alternate repos

In some build and test scenarios, it's desirable to fetch alternate proxy
releases during the build process.

This change updates the proxy container image build tooling to support the
LINKERD2_PROXY_REPO and LINKERD2_PROXY_GITHUB_TOKEN environment variables. These
may be set to the desired repository and a GitHub personal access token,
respectively.

When these are unset, the default behavior is unchanged.

diff --git a/bin/git-commit-proxy-version b/bin/git-commit-proxy-version
--- a/bin/git-commit-proxy-version
+++ b/bin/git-commit-proxy-version
@@ -33,11 +33,15 @@ new_proxy_rev="release/$new_proxy_version"
 # Checkout the linkerd2-proxy repo to resolve the new proxy version to a SHA
 # and obtain the commit log since the prior version.
 tmp=$(mktemp -d -t l2-proxy.XXX)
-git clone --depth=500 https://github.com/linkerd/linkerd2-proxy "$tmp"
+repo="${LINKERD2_PROXY_REPO:-linkerd/linkerd2-proxy}"
+git clone --depth=500 https://github.com/"$repo" "$tmp"
 cd "$tmp"
 
 if ! git rev-parse --verify --quiet "${old_proxy_rev}" ; then
-    echo "The old proxy-version ${old_proxy_version} does not exist in the last 100 proxy commits." >&2
+    git pull --tags
+fi
+if ! git rev-parse --verify --quiet "${old_proxy_rev}" ; then
+    echo "The old proxy-version ${old_proxy_version} not found." >&2
     exit 2
 fi
 
