bin/shellcheck-all: Add filename/shebang check
We only run shellcheck for files that contain a #!/usr/bin/env shebang
with either bash or sh. If a new shellscript file is added that has the
.sh extension but either lacks shebang or has something other than that,
shellcheck will not be run for that file. Then there is a risk that
by mistake such a file slips into the repo under the radar.

This patch adds a check for all .sh files to make sure they have a
corresponding shebang in order for them to be passed to shellcheck.

Change-Id: I24235e672dd82c7c73df6fe6c8beda2a579bd187
Signed-off-by: Joakim Roubert <joakimr@axis.com>

diff --git a/bin/shellcheck-all b/bin/shellcheck-all
--- a/bin/shellcheck-all
+++ b/bin/shellcheck-all
@@ -5,6 +5,16 @@ set -eu
 bindir=$( cd "${0%/*}" && pwd )
 rootdir=$( cd "$bindir"/.. && pwd )
 
+# Make sure all files with the .sh extension are shellscripts and have a
+# proper shebang
+shebangpattern='#!/usr/bin/env (bash|sh)'
+find "$rootdir" -name \*.sh -type f | while IFS= read -r file; do
+    head -1 "$file" | grep -qE "$shebangpattern\$" || {
+        echo "ERROR: No valid '$shebangpattern' shebang found in '$file'" >&2
+        exit 1
+    }
+done
+
 # For more information on shellcheck failures:
 # https://github.com/koalaman/shellcheck/wiki/Checks
 
