Fix whitespace path handling in non-docker (build) scripts
Handling of whitespace paths was not fully implemented; this patch adds
the missing pieces. Also, only use bash where bash-specific
functionality is used/needed.

Change-Id: Ia5846443a8029c7aa039cb1cce4411438dfef54b
Signed-off-by: Joakim Roubert <joakimr@axis.com>

diff --git a/bin/test-scale b/bin/test-scale
--- a/bin/test-scale
+++ b/bin/test-scale
@@ -17,56 +17,60 @@ REPLICAS=5
 
 # TODO: share these functions with test-run
 
-function check_linkerd_binary(){
-    printf "Checking the linkerd binary..."
-    if [[ "$linkerd_path" != /* ]]; then
-        printf "\\n[%s] is not an absolute path\\n" "$linkerd_path"
-        exit 1
-    fi
+check_linkerd_binary(){
+    printf 'Checking the linkerd binary...'
+    case "$linkerd_path" in
+        /*)
+            ;;
+        *)
+            printf '\\n[%s] is not an absolute path\\n' "$linkerd_path"
+            exit 1
+            ;;
+    esac
     if [ ! -x "$linkerd_path" ]; then
-        printf "\\n[%s] does not exist or is not executable\\n" "$linkerd_path"
+        printf '\\n[%s] does not exist or is not executable\\n' "$linkerd_path"
         exit 1
     fi
     exit_code=0
     "$linkerd_path" version --client > /dev/null 2>&1 || exit_code=$?
     if [ $exit_code -ne 0 ]; then
-        printf "\\nFailed to run linkerd version command\\n"
+        printf '\\nFailed to run linkerd version command\\n'
         exit $exit_code
     fi
-    printf "[ok]\\n"
+    printf '[ok]\\n'
 }
 
-function check_if_k8s_reachable(){
-    printf "Checking if there is a Kubernetes cluster available..."
+check_if_k8s_reachable(){
+    printf 'Checking if there is a Kubernetes cluster available...'
     exit_code=0
     kubectl --request-timeout=5s get ns > /dev/null 2>&1 || exit_code=$?
     if [ $exit_code -ne 0 ]; then
-        printf "\\nFailed to connect to Kubernetes cluster\\n"
+        printf '\\nFailed to connect to Kubernetes cluster\\n'
         exit $exit_code
     fi
-    printf "[ok]\\n"
+    printf '[ok]\\n'
 }
 
 linkerd_path=$1
 
 if [ -z "$linkerd_path" ]; then
-    echo "usage: $(basename "$0") /path/to/linkerd [namespace]" >&2
+    echo "usage: ${0##*/} /path/to/linkerd [namespace]" >&2
     exit 64
 fi
 
 check_linkerd_binary
 check_if_k8s_reachable
 
-linkerd_version=$($linkerd_path version --client --short)
+linkerd_version=$("$linkerd_path" version --client --short)
 linkerd_namespace=${2:-l5d-scale}
 
 #
 # Deploy Linkerd
 #
 
-$linkerd_path -l $linkerd_namespace install | kubectl apply -f -
-$linkerd_path -l $linkerd_namespace check --expected-version=$linkerd_version
-$linkerd_path -l $linkerd_namespace install-sp | kubectl apply -f -
+"$linkerd_path" -l $linkerd_namespace install | kubectl apply -f -
+"$linkerd_path" -l $linkerd_namespace check --expected-version=$linkerd_version
+"$linkerd_path" -l $linkerd_namespace install-sp | kubectl apply -f -
 
 #
 # Deploy Books
@@ -101,7 +105,7 @@ END
 BOOKS_APP=$(echo "${BOOKS_APP/$traffic_param/$sleep_param}")
 
 # inject
-BOOKS_APP=$(echo "$BOOKS_APP" | $linkerd_path -l $linkerd_namespace inject -)
+BOOKS_APP=$(echo "$BOOKS_APP" | "$linkerd_path" -l $linkerd_namespace inject -)
 
 # deploy books apps to N namespaces
 for i in $(eval echo {1..$NAMESPACES}); do
@@ -121,14 +125,14 @@ EMOJIVOTO=$(curl -s https://run.linkerd.io/emojivoto.yml)
 
 # delete namespace
 EMOJIVOTO=$(echo "$EMOJIVOTO" | tail -n +6)
-emojins="namespace: emojivoto"
+emojins='namespace: emojivoto'
 EMOJIVOTO=$(echo "${EMOJIVOTO//$emojins/}")
-emojins=".emojivoto:"
-newns=":"
+emojins=.emojivoto:
+newns=:
 EMOJIVOTO=$(echo "${EMOJIVOTO//$emojins/$newns}")
 
 # inject
-EMOJIVOTO=$(echo "$EMOJIVOTO" | $linkerd_path -l $linkerd_namespace inject -)
+EMOJIVOTO=$(echo "$EMOJIVOTO" | "$linkerd_path" -l $linkerd_namespace inject -)
 
 for i in $(eval echo {1..$NAMESPACES}); do
     emojins=$linkerd_namespace-emoji-$i
@@ -161,4 +165,4 @@ done
 # Watch performance
 #
 
-watch $linkerd_path -l $linkerd_namespace stat ns
+watch "$linkerd_path" -l $linkerd_namespace stat ns
