Add unit test for `helm install`
Ref #3143

Also added `exit_on_err` in `bin/test-run`, for DRYing code for failing
fast after tests (we weren't doing that if install_test.go failed during
the non-upgrade).

Note this adds 3 mins of testing in my laptop (out of a total of 13
mins). Would be great if we could consider running some of these in
parallel clusters in the next integration tests infra revamp :wink:

Signed-off-by: Alejandro Pedraza <alejandro@buoyant.io>

diff --git a/bin/test-run b/bin/test-run
--- a/bin/test-run
+++ b/bin/test-run
@@ -80,6 +80,13 @@ function run_upgrade_test() {
     run_test "$test_directory/install_test.go" -failfast --upgrade-from-version=$stable_version --linkerd-namespace=$stable_namespace
 }
 
+function exit_on_err() {
+  if [ $exit_code -ne 0 ]; then
+    printf "\\n=== FAIL: %s\\n" "$@"
+    exit $exit_code
+  fi
+}
+
 linkerd_path=$1
 if [ -z "$linkerd_path" ]; then
     echo "usage: $(basename "$0") /path/to/linkerd [namespace] [k8s-context]" >&2
@@ -106,15 +113,23 @@ printf "Testing Linkerd version [%s] namespace [%s] k8s-context [%s]\\n" "$linke
 # fail subsequent tests. `cleanup` is not called if this test failed so that
 # there is a chance to debug the problem
 run_upgrade_test "$linkerd_namespace"-upgrade || exit_code=$?
-if [ $exit_code -ne 0 ]; then
-  printf "\\n=== FAIL: Can't upgrade to version $linkerd_version\\n"
-  exit $exit_code
-fi
+exit_on_err "can't upgrade to version $linkerd_version"
 cleanup
 
-# run the rest of the test suite. `cleanup` is not called if this test failed
-# so that there is a chance to debug the problem
+rootdir="$( cd $bindir/.. && pwd )"
+helm_path=$bindir/helm
+helm_chart=$rootdir/charts/linkerd2
+helm_release_name=$linkerd_namespace-test
+$helm_path init --wait
+run_test "$test_directory/install_test.go" -failfast --linkerd-namespace=$linkerd_namespace-helm \
+    --helm-path=$helm_path --helm-chart=$helm_chart --helm-release=$helm_release_name || exit_code=$?
+exit_on_err "failed using helm install|delete"
+cleanup
+$helm_path delete --purge $helm_release_name
+
 run_test "$test_directory/install_test.go" -failfast --linkerd-namespace=$linkerd_namespace || exit_code=$?
+exit_on_err "failed install"
+
 for test in $(find "$test_directory" -mindepth 2 -name '*_test.go'); do
     run_test "$test" --linkerd-namespace=$linkerd_namespace || exit_code=$?
 done
@@ -123,6 +138,7 @@ if [ $exit_code -eq 0 ]; then
     printf "\\n=== PASS: all tests passed\\n"
     cleanup
 else
+    # `cleanup` is not called so that there is a chance to debug the problem
     printf "\\n=== FAIL: at least one test failed\\n"
 fi
 
