Require linkerd path argument
Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>

diff --git a/bin/test-clouds-cleanup b/bin/test-clouds-cleanup
--- a/bin/test-clouds-cleanup
+++ b/bin/test-clouds-cleanup
@@ -13,6 +13,13 @@
 
 set -e
 
+if [ $# -ne 1 ]; then
+  echo "Error: accepts 1 argument"
+  echo "Usage:"
+  echo "  "${0##*/}" /path/to/linkerd"
+  exit 1
+fi
+
 for CLUSTER in 'AKS' 'DO' 'EKS' 'GKE'; do
   if [ -z "${!CLUSTER}" ]; then
     echo "\$$CLUSTER not set" >&2
@@ -23,5 +30,5 @@ done
 for CLUSTER in $AKS $DO $EKS $GKE
 do
   printf '\n%s\n' "$CLUSTER"
-  bin/test-cleanup --context "$CLUSTER"
+  bin/test-cleanup --context "$CLUSTER" $1
 done
