fix tests

diff --git a/bin/test-run b/bin/test-run
--- a/bin/test-run
+++ b/bin/test-run
@@ -37,8 +37,8 @@ function run_test(){
 
 linkerd_path=$1
 
-# echo "TEST TESTING FAIL bin/test-run"
-# exit 1
+echo "TEST TESTING FAIL bin/test-run"
+exit 1
 
 if [ -z "$linkerd_path" ]; then
     echo "usage: $(basename "$0") /path/to/linkerd [namespace]" >&2
