Start running integration tests in CI
Signed-off-by: Kevin Lingerfelt <kl@buoyant.io>

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -12,6 +12,8 @@ stages:
   - name: test
   - name: docker-deploy
     if: branch = master AND type != pull_request
+  - name: integration-test
+    if: branch = master AND type != pull_request
 
 jobs:
   include:
@@ -141,6 +143,64 @@ jobs:
         - bin/docker-retag-all $CONDUIT_TAG master && bin/docker-push master
         - target/cli/linux/conduit install --conduit-version=$CONDUIT_TAG |tee conduit.yml
         - kubectl -n conduit apply -f conduit.yml --prune --selector='conduit.io/control-plane-component'
+
+    # Run integration tests after container images have been published.
+    - stage: integration-test
+
+      language: go
+      go: "1.10.2"
+      go_import_path: github.com/runconduit/conduit
+
+      cache:
+        directories:
+          - vendor
+          - "$HOME/google-cloud-sdk/"
+          - "$HOME/.cache"
+
+      install:
+        - ./bin/dep ensure -vendor-only -v
+        - ./bin/dep status -v
+
+        - |
+          # Install gcloud and kubectl.
+          dir="${CLOUDSDK_INSTALL_DIR:-${HOME}}/google-cloud-sdk"
+          export CLOUDSDK_CORE_DISABLE_PROMPTS=1
+          if [ -d "$dir/bin" ]; then
+              . "$dir/path.bash.inc"
+              gcloud components update
+          else
+              rm -rf "$dir"
+              curl https://sdk.cloud.google.com | bash
+              . "$dir/path.bash.inc"
+          fi
+          gcloud components install kubectl
+        - |
+          # Configure gcloud with a service account.
+          openssl aes-256-cbc -K $encrypted_6af64675f81c_key -iv $encrypted_6af64675f81c_iv -in .gcp.json.enc -out .gcp.json -d
+          gcloud auth activate-service-account --key-file .gcp.json
+          gcloud config set core/project "$GCP_PROJECT"
+          gcloud config set compute/zone "$GCP_ZONE"
+          gcloud config set container/cluster "$GKE_CLUSTER"
+        - |
+          # Get a kubernetes context.
+          (. bin/_gcp.sh ; get_k8s_ctx "$GCP_PROJECT" "$GCP_ZONE" "$GKE_CLUSTER")
+        - gcloud version
+        - kubectl version --short
+
+      script:
+        - |
+          # Run tests and cleanup afterward.
+          exit_code=0
+          cleanup_exit_code=0
+          version=$(./bin/go-run cli version --client --short)
+          namespace=conduit-$(echo $version | tr -cd '[:alnum:]-')
+          ./bin/test-run $(pwd)/.gorun $namespace || exit_code=$?
+          ./bin/test-cleanup $namespace || cleanup_exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            exit $exit_code;
+          else
+            exit $cleanup_exit_code;
+          fi
 
   # If we want to start building everything against bleeding-edge Rust nightly, we'll have
   # to enable:
