ci: Use devcontainer tooling in CI
Our devcontainers pin versions of all of the tools we need to build &
test the project, but these tools are not necessarily kept in sync with
those in our devcontainer.

This change introduces new variants of our devcontainer image that can
be pre-bundled with Go or Rust tooling (with fairly minimal container
images). Various CI workflows are updated to use the same tooling
versions that are used by our devcontainer, and a CI workflow is added
to ensure that these versions stay in sync. Some workflows are NOT
updated--especially those that invoke `docker`--since the docker
environment is severely limited when running inside of a container.

Furthermore, this change does the following:

* Update shellcheck to v0.8.0;
* Update `bin/shellcheck-all` to exclude irrelevant files (that are not
  part of the project);
* Add `helm` and `helm-docs` to the devcontainer;
* Update `helm` to v3.9.1
* Update `helm-docs` to v1.11.0
* Include tools like `just`, `cargo-action-fmt`, and `cargo-nextest` in
  our Rust image
* Add a `just` recipe that builds (and optionally publish) the
  appropriate devcontainer images

Signed-off-by: Oliver Gould <ver@buoyant.io>

diff --git a/.github/workflows/github_actions_lint.yml b/.github/workflows/github_actions_lint.yml
--- a/.github/workflows/github_actions_lint.yml
+++ b/.github/workflows/github_actions_lint.yml
@@ -4,38 +4,52 @@ on:
   pull_request:
     paths:
       - .github/**
+      - .devcontainer/devcontainer.json
 
 permissions:
   contents: read
 
-env:
-  # Pin 'actionlint' to v1.6.15
-  ACTION_LINT_VERSION: 1.6.15
 jobs:
   lint-workflows:
     runs-on: ubuntu-20.04
     name: Lint GitHub Actions
     timeout-minutes: 30
+    container: ghcr.io/linkerd/dev:v19-actionlint
     steps:
-      - name: Checkout code
-        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
-      - name: Install actionlint
-        shell: bash
-        run: |
-          # Install pinned version of actionlint and save binary in bin/ directory
-          bin/scurl -v "https://raw.githubusercontent.com/rhysd/actionlint/v${ACTION_LINT_VERSION}/scripts/download-actionlint.bash" \
-          | bash -s -- "${ACTION_LINT_VERSION}" /usr/local/bin
-          chmod 755 /usr/local/bin/actionlint
+      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
       - name: Run actionlint
-        shell: bash
         run: |
           # Run actionlint and format errors to fit GitHub Action's style
-          # To print multiline text in annotations toolkit, we replace '\n'
-          # with '%0A' (urlencoded newline, see https://github.com/actions/toolkit/issues/193)
-          # Shellcheck 2016 is supressed so template args can be passed in
-          # Shellcheck 1090 is supressed to avoid using location directives when sourcing scripts
-          actionlint -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' -ignore 'SC2016:' -ignore 'SC1090:'
+          #
+          # To print multiline text in annotations, we replace '\n' with
+          # '%0A' (urlencoded newline, see https://github.com/actions/toolkit/issues/193)
+          #
+          # * SC1090: avoid using location directives when sourcing scripts
+          # * SC2016: so template args can be passed in
+          actionlint \
+            -verbose \
+            -format '{{range $err := .}}::error file={{$err.Filepath}},line={{$err.Line}},col={{$err.Column}}::{{$err.Message}}%0A```%0A{{replace $err.Snippet "\\n" "%0A"}}%0A```\n{{end}}' \
+            -ignore 'SC1090:' \
+            -ignore 'SC2016:' \
+            .github/workflows/*
 
-          
+  devcontainer-versions:
+    runs-on: ubuntu-latest
+    name: Check devcontainer versions
+    container: ghcr.io/linkerd/dev:v19-yq
+    steps:
+      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
+      - name: Scan workflows for other Devcontainer image versions
+        run: |
+          # Strip jsonc comments because `jq` doesn't support them.
+          image=$(sed -E '/^\s*\/\/.*/d' .devcontainer/devcontainer.json |jq -Mr .image)
+          for f in .github/workflows/* ; do
+            for i in $(yq '.jobs.* | .container.image // .container // "" | match("ghcr.io/linkerd/dev:v[0-9]+").string' < "$f") ; do
+              if [ "$i" != "$image" ]; then
+                echo "::error file=$f::Workflow '$f' uses incorrect Devcontainer image '$i'"
+                exit 1
+              fi
+            done
+          done
 
 
