ci: Update Go workflow to always run (#12273)
This change adds a 'go-ok' step that can become required.

This change also adds retries for the flakey
TestEndpointProfileTranslator/Handles_overflow test.

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -1,19 +1,31 @@
 name: Go
-
-on:
-  pull_request:
-    paths:
-      - .github/workflows/go.yml
-      - go.sum
-      - "**/*.go"
-      - "**/*.golden"
-      - "**/charts/**"
+on: pull_request
 
 permissions:
   contents: read
 
 jobs:
+  meta:
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: tj-actions/changed-files@77af4bed286740ef1a6387dc4e4e4dec39f96054
+        id: changed
+        with:
+          files: |
+            .github/workflows/go.yml
+            go.sum
+            **/*.go
+            **/*.golden
+            **/charts/**
+          files_ignore: |
+            **/Chart.yaml
+            **/README*
+    outputs:
+      changed: ${{ steps.changed.outputs.any_changed }}
+
   go-lint:
+    needs: meta
+    if: needs.meta.outputs.changed == 'true'
     timeout-minutes: 10
     runs-on: ubuntu-22.04
     container: ghcr.io/linkerd/dev:v43-go
@@ -23,6 +35,8 @@ jobs:
       - run: just go-lint --verbose --timeout=10m
 
   go-format:
+    needs: meta
+    if: needs.meta.outputs.changed == 'true'
     timeout-minutes: 10
     runs-on: ubuntu-22.04
     container: ghcr.io/linkerd/dev:v43-go
@@ -32,6 +46,8 @@ jobs:
       - run: just go-fmt
 
   go-test:
+    needs: meta
+    if: needs.meta.outputs.changed == 'true'
     timeout-minutes: 10
     runs-on: ubuntu-22.04
     container: ghcr.io/linkerd/dev:v43-go
@@ -40,3 +56,35 @@ jobs:
       - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
       - run: just go-fetch
       - run: just go-test
+
+  # There's currently one flakey test we want to retry in particular:
+  # TestEndpointProfileTranslator/Handles_overflow
+  go-test-retry:
+    needs: go-test
+    if: failure() && fromJSON(github.run_attempt) < 3
+    runs-on: ubuntu-22.04
+    permissions:
+      actions: write
+    env:
+      GH_REPO: ${{ github.repository }}
+      GH_TOKEN: ${{ github.token }}
+      GH_DEBUG: api
+      REF: ${{ github.head_ref }}
+    steps:
+      - run: gh workflow run rerun.yml -F 'run_id=${{ github.run_id }}' --ref "$REF"
+
+  go-ok:
+    needs: [go-lint, go-format, go-test]
+    if: always()
+    runs-on: ubuntu-22.04
+    steps:
+      - name: Results
+        run: |
+          echo 'go-lint: ${{ needs.go-lint.result }}'
+          echo 'go-format: ${{ needs.go-format.result }}'
+          echo 'go-test: ${{ needs.go-test.result }}'
+
+      - name: Verify jobs
+        # All jobs must succeed or be skipped.
+        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
+        run: exit 1
