ci: fix default Rust toolchain in `test-policy`
PR #11528 changed the `rust-toolchain` file to use the TOML format
rather than the plaintext format. Unfortunately, this broke the
`test-policy` CI job, which `cat`s the contents of the `rust-toolchain`
file to determine which Rust version to install, and that file now no
longer exists (since it's now in `rust-toolchain.toml`). See:
https://github.com/linkerd/linkerd2/actions/runs/6649430068/job/18068192854?pr=11535

This branch fixes that by changing the CI job to use a regex to extract
the Rust toolchain version instead.

diff --git a/.github/workflows/integration.yml b/.github/workflows/integration.yml
--- a/.github/workflows/integration.yml
+++ b/.github/workflows/integration.yml
@@ -187,8 +187,18 @@ jobs:
       - name: Setup deps
         shell: bash
         run: |
+          # Extract current Rust version from the toolchain file.
+          version_regex='channel = "([0-9]+\.[0-9]+\.[0-9]+)"'
+          toolchain=$(cat rust-toolchain.toml)
+          if [[ $toolchain =~ $version_regex ]]; then
+            toolchain_version=${BASH_REMATCH[1]}
+          else
+            echo "::error file=rust-toolchain.toml::failed to parse rust-toolchain.toml"
+            exit 1
+          fi
+
           rm -rf "$HOME/.cargo"
-          bin/scurl -v https://sh.rustup.rs | sh -s -- -y --default-toolchain "$(cat rust-toolchain)"
+          bin/scurl -v https://sh.rustup.rs | sh -s -- -y --default-toolchain "$toolchain_version"
           # shellcheck disable=SC1090
           source ~/.cargo/env
           echo "PATH=$PATH" >> "$GITHUB_ENV"
