ci: Verify the devcontainer configuration in CI (#7700)
This change adds a _devcontainer_ CI workflow that only runs when the
devcontainer config or rust-toolchain changes. It ensures that the
devcontainer uses the same Rust toolchain as the repo, that the
devcontainer dockerfiles builds successfully, and that the devcontainer
config references a real, published image.

Signed-off-by: Oliver Gould <ver@buoyant.io>
(cherry picked from commit 325bf7d917029ee0dcd9335f9d22c3845ee8fe95)
Signed-off-by: Oliver Gould <ver@buoyant.io>

diff --git a/.github/workflows/policy_controller.yml b/.github/workflows/policy_controller.yml
--- a/.github/workflows/policy_controller.yml
+++ b/.github/workflows/policy_controller.yml
@@ -82,3 +82,31 @@ jobs:
       - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
       - run: cargo test --workspace --no-run
       - run: cargo test --workspace
+
+  rust-toolchain:
+    name: rust toolchain
+    runs-on: ubuntu-latest
+    timeout-minutes: 2
+    steps:
+      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
+      - run: |
+          ex=0
+
+          # Check this workflow against the version in rust-toolchain.
+          versions=$(sed -nE 's|.*docker://(.*/)?rust:([^ #]+).*|\2|p' .github/workflows/policy_controller.yml)
+          for mismatch in $(echo "$versions" | grep -vF "$(cat rust-toolchain)" || true) ; do
+            echo "::error file=.github/workflows/policy_controller.yml::Workflow uses incorrect rust version(s): $mismatch"
+            ex=$((ex + 1))
+          done
+
+          # Check the policy-controller dockerfiles workflow against the version
+          # in rust-toolchain.
+          for f in policy-controller/*.dockerfile ; do
+            versions=$(sed -nE 's|ARG RUST_IMAGE=(.*/)?rust:([^ #]+).*|\2|p' "$f")
+            for mismatch in $(echo "$versions" | grep -vF "$(cat rust-toolchain)" || true) ; do
+              echo "::error file=\"$f\"::$f uses incorrect rust version(s): $mismatch"
+              ex=$((ex + 1))
+            done
+          done
+
+          exit $ex
