Test the policy controller admission webhook
The policy controller has an validating webhook for `Server` resources,
but this functionality is not really tested.

Before adding more policy resources that need validation, let's add an
integration test that exercises resource validation. The initial test is
pretty simplistic, but this is just setup.

These test also help expose two issues:

1. The change in 8760c5f--to solely use the index for validation--is
   problematic, especially in CI where quick updates can pass validation
   when they should not. This is fixed by first checking the index and
   falling back to the API. This means we'll do redundant checks in many
   cases, but the actual checking is fairly cheap. We still avoid the
   API call if a conflict is detected using the index.
2. Our pod selector overlap detection is overly simplistic. This change
   updates it to at least detect when a server selects _all_ pods.
   There's probably more we can do here in followup changes.

Tests are added in a new `policy-test` crate that only includes these
tests and the utiltities they need. This crate is excluded when running
unit tests and is only executed when it has a Kubernetes cluster it can
execute against. A temporary namespace is created before each test is
run and deleted as the test completes.

The policy controller's CI workflow is updated to build the core control
plane, run a k3d cluster, and exercise tests. This workflow has minimal
dependencies on the existing script/CI tooling so that the dependencies
are explicit and we can avoid some of the complexity of the existing
test infrastructure.

Signed-off-by: Oliver Gould <ver@buoyant.io>

diff --git a/.github/workflows/policy_controller.yml b/.github/workflows/policy_controller.yml
--- a/.github/workflows/policy_controller.yml
+++ b/.github/workflows/policy_controller.yml
@@ -3,12 +3,15 @@ name: Policy Controller
 on:
   pull_request:
     paths:
-      - 'Cargo.lock'
-      - 'Cargo.toml'
-      - 'deny.toml'
-      - 'rust-toolchain'
-      - 'policy-controller/**'
-      - '.github/workflows/policy_controller.yml'
+      - .github/workflows/policy_controller.yml
+      - Cargo.lock
+      - Cargo.toml
+      - charts/linkerd-control-plane/templates/destination-rbac.yaml
+      - charts/linkerd-crds/templates/policy/**
+      - deny.toml
+      - policy-controller/**
+      - policy-test/**
+      - rust-toolchain
 
 permissions:
   contents: read
@@ -58,7 +61,7 @@ jobs:
       - run: |
           bin/scurl -o /usr/local/bin/cargo-action-fmt "https://github.com/olix0r/cargo-action-fmt/releases/download/release%2F${CARGO_ACTION_FMT_VERSION}/cargo-action-fmt-x86_64-unknown-linux-gnu"
           chmod 755 /usr/local/bin/cargo-action-fmt
-      - run: cargo fetch
+      - run: cargo fetch --locked
       - run: cargo clippy --frozen --all --no-deps --message-format=json | cargo-action-fmt
 
   check:
@@ -71,7 +74,7 @@ jobs:
       - run: |
           bin/scurl -o /usr/local/bin/cargo-action-fmt "https://github.com/olix0r/cargo-action-fmt/releases/download/release%2F${CARGO_ACTION_FMT_VERSION}/cargo-action-fmt-x86_64-unknown-linux-gnu"
           chmod 755 /usr/local/bin/cargo-action-fmt
-      - run: cargo fetch
+      - run: cargo fetch --locked
       # Check each crate independently to ensure its Cargo.toml is sufficient.
       - run: |
           for toml in $(find . -mindepth 2 -name Cargo.toml | sort -r)
@@ -89,9 +92,9 @@ jobs:
       image: docker://rust:1.59.0
     steps:
       - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
-      - run: cargo fetch
-      - run: cargo test --workspace --frozen --no-run
-      - run: cargo test --workspace --frozen
+      - run: cargo fetch --locked
+      - run: cargo test --workspace --exclude=linkerd-policy-test --frozen --no-run
+      - run: cargo test --workspace --exclude=linkerd-policy-test --frozen
 
   rust-toolchain:
     name: rust toolchain
@@ -120,3 +123,122 @@ jobs:
           done
 
           exit $ex
+
+  docker_build:
+    runs-on: ubuntu-20.04
+    strategy:
+      matrix:
+        component:
+          - controller
+          - policy-controller
+          - proxy
+    name: Docker build (${{ matrix.component }})
+    timeout-minutes: 30
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
+      - uses: ./.github/actions/docker-build
+        with:
+          docker-registry: ghcr.io/linkerd
+          docker-target: linux-amd64
+          component: ${{ matrix.component }}
+      - name: Create artifact with CLI and image archives
+        run: |
+          mkdir -p /home/runner/archives
+          docker save "ghcr.io/linkerd/${{ matrix.component }}:$TAG" \
+            >/home/runner/archives/${{ matrix.component }}.tar
+      - name: Upload artifact
+        uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
+        with:
+          name: image-archives
+          path: /home/runner/archives
+
+  integration:
+    needs: [docker_build]
+    name: Policy controller integration
+    runs-on: ubuntu-20.04
+    timeout-minutes: 20
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846
+
+      - name: Install kubectl
+        run: |
+          dir=$(mktemp -d)
+          version=$(bin/scurl https://dl.k8s.io/release/stable.txt)
+          bin/scurl -vo $dir/kubectl "https://dl.k8s.io/release/${version}/bin/linux/amd64/kubectl"
+          chmod 755 $dir/kubectl
+          sudo mv $dir/kubectl /usr/local/bin/kubectl
+          cli_version=$(kubectl version --client --short | sed -ne 's/^Client Version: //p')
+          if [[ "$version" != "$cli_version" ]] ; then
+            echo "::error::kubectl version is $cli_version; expected $version"
+            exit 1
+          fi
+          kubectl version --client
+      - name: Install k3d
+        run: |
+          bin/scurl -v https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
+          k3d --version
+
+      # Go is needed to build the CLI.
+      - uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
+        with:
+          go-version: '1.17'
+      - name: Build the Linkerd CLI
+        run: |
+          # Compile the linkerd CLI
+          bin/linkerd version --short --client
+
+      - name: Create cluster
+        run: |
+          k3d cluster create --no-lb --k3s-arg "--disable=servicelb,traefik@server:0"
+          kubectl version --short
+
+      - name: Download image archives
+        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741
+        with:
+          name: image-archives
+          path: image-archives
+      - name: Load images
+        run: |
+          docker load <image-archives/controller.tar
+          docker load <image-archives/policy-controller.tar
+          docker load <image-archives/proxy.tar
+          docker pull ghcr.io/linkerd/proxy-init:v1.5.3
+          docker image ls | grep ghcr.io/linkerd
+          tag="$(CI_FORCE_CLEAN=1 bin/root-tag)"
+          k3d image import \
+            ghcr.io/linkerd/controller:$tag \
+            ghcr.io/linkerd/policy-controller:$tag \
+            ghcr.io/linkerd/proxy:$tag \
+            ghcr.io/linkerd/proxy-init:v1.5.3
+
+      - run: bin/linkerd check --pre --wait=1m
+      - run: bin/linkerd install | kubectl apply -f -
+        env:
+          LINKERD_DOCKER_REGISTRY: ghcr.io/linkerd
+      - name: Wait for pods to be ready
+        run: |
+          if ! kubectl wait pods -n linkerd -l linkerd.io/control-plane-ns --for condition=Ready --timeout=1m ; then
+            kubectl describe po -n linkerd >&2
+            exit 1
+          fi
+      - run: bin/linkerd check --wait=1m
+
+      - name: Install rust
+        run: |
+          rm -rf $HOME/.cargo
+          bin/scurl -v https://sh.rustup.rs \
+            | sh -s -- -y --default-toolchain $(cat rust-toolchain)
+          source $HOME/.cargo/env
+          echo "PATH=$PATH" >> $GITHUB_ENV
+          cargo version
+
+      - name: Install cargo-action-fmt
+        run: |
+          bin/scurl -o /usr/local/bin/cargo-action-fmt "https://github.com/olix0r/cargo-action-fmt/releases/download/release%2F${CARGO_ACTION_FMT_VERSION}/cargo-action-fmt-x86_64-unknown-linux-gnu"
+          chmod 755 /usr/local/bin/cargo-action-fmt
+
+      - run: cargo fetch --locked
+      - run: cargo test -p linkerd-policy-test --frozen --no-run | cargo-action-fmt
+      - run: cargo test -p linkerd-policy-test --frozen
